### PR TITLE
[CELEBORN-912][FOLLOWUP] Support columnar shuffle for Spark 3.5

### PR DESCRIPTION
**Pull request by SteNicholas**
### What changes were proposed in this pull request?

Introduce `spark-3.5-columnar-shuffle` module to support columnar shuffle for Spark 3.5.

### Why are the changes needed?

#1850 does not support columnar shuffle for Spark 3.5, in which version building `spark-3-columnar-shuffle` module has compilation error. The compilation error is caused by https://github.com/apache/spark/pull/40784, which incompatible changes move `InternalType` from `AtomicType` to `PhysicalDataType`.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CI.

### CODE REVIEW

**Comment by SteNicholas** [comment]
Ping @pan3793, @kerwin-zk, @zhouyifan279.

**Review by kerwin-zk — APPROVED** [review]
LGTM.Thanks!
